"""Integration tests for the candidate-pool storage repositories.

Each test runs inside the savepoint-isolated ``db_session`` fixture
defined in :mod:`tests.storage.integration.conftest`. The fixture spins
up a disposable PostgreSQL container via Testcontainers and rolls back
every change after the test, so the tests in this file can share a
single container without leaking data between cases.

The fixtures create the ``analytics.candidate_pool_runs`` and
``analytics.candidate_pool_items`` tables (along with the rest of the
PR-01 / PR-02 schema) directly through ``Base.metadata.create_all``.
The repositories only rely on the SQLAlchemy model so the migration
``20260731_0003`` is exercised on a real PostgreSQL deployment rather
than re-implemented in the fixture.
"""

from __future__ import annotations

from collections.abc import Iterator
from datetime import UTC, date, datetime
from decimal import Decimal
from uuid import UUID, uuid4

import pytest
from invest_domain.candidate_pool.models import (
    CandidatePoolItem,
    CandidatePoolRun,
    CandidatePoolStatus,
    ExclusionReason,
    RuleOutcome,
    RuleSeverity,
)
from invest_domain.instruments import InstrumentId
from invest_storage import (
    SqlAlchemyCandidatePoolItemRepository,
    SqlAlchemyCandidatePoolRunRepository,
)
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session


@pytest.fixture()
def candidate_pool_run_repository(
    db_session: Session,
) -> Iterator[SqlAlchemyCandidatePoolRunRepository]:
    """Yield a fresh :class:`SqlAlchemyCandidatePoolRunRepository` per test."""

    yield SqlAlchemyCandidatePoolRunRepository(db_session)


@pytest.fixture()
def candidate_pool_item_repository(
    db_session: Session,
) -> Iterator[SqlAlchemyCandidatePoolItemRepository]:
    """Yield a fresh :class:`SqlAlchemyCandidatePoolItemRepository` per test."""

    yield SqlAlchemyCandidatePoolItemRepository(db_session)


def _utc(year: int, month: int, day: int, hour: int = 0) -> datetime:
    return datetime(year, month, day, hour, tzinfo=UTC)


def _insert_instrument(db_session: Session, *, symbol: str) -> UUID:
    """Insert a minimal ``core.instruments`` row the items can reference.

    Returns the UUID generated by the database; the ``db_session``
    caller flushes the change so the row is visible to subsequent
    ``SELECT`` queries inside the same savepoint.
    """

    inserted = db_session.execute(
        text(
            "INSERT INTO core.instruments (id, symbol, exchange, name, "
            "instrument_type, currency, status, is_active, created_at, "
            "updated_at) VALUES (gen_random_uuid(), :symbol, 'SSE', :symbol, "
            "'ETF', 'CNY', 'active', true, now(), now()) RETURNING id"
        ),
        {"symbol": symbol},
    ).scalar_one()
    db_session.flush()
    return inserted


def _new_calculated_run(
    *,
    trade_date: date = date(2026, 7, 31),
    algorithm_key: str = "candidate_pool.v1",
    algorithm_version: str = "v1.0",
    parameter_set_key: str = "default",
    parameter_hash: str = "a" * 64,
    input_snapshot_id: UUID | None = None,
    input_row_count: int = 100,
    included_count: int = 10,
) -> CandidatePoolRun:
    return CandidatePoolRun(
        id=uuid4(),
        trade_date=trade_date,
        algorithm_key=algorithm_key,
        algorithm_version=algorithm_version,
        parameter_set_key=parameter_set_key,
        parameter_hash=parameter_hash,
        input_snapshot_id=input_snapshot_id or uuid4(),
        input_row_count=input_row_count,
        included_count=included_count,
        status=CandidatePoolStatus.CALCULATED,
        created_at=_utc(2026, 7, 31, 9),
    )


def test_add_persists_calculated_run(
    candidate_pool_run_repository: SqlAlchemyCandidatePoolRunRepository,
) -> None:
    """``add`` writes every column of the candidate-pool run row."""

    run = _new_calculated_run()

    persisted = candidate_pool_run_repository.add(
        run, quality_summary={"coverage": 0.97, "rule_errors": 0}
    )

    assert persisted.id == run.id
    assert persisted.status == CandidatePoolStatus.CALCULATED
    assert persisted.trade_date == run.trade_date
    assert persisted.algorithm_key == run.algorithm_key
    assert persisted.algorithm_version == run.algorithm_version
    assert persisted.parameter_set_key == run.parameter_set_key
    assert persisted.parameter_hash == run.parameter_hash
    assert persisted.input_snapshot_id == run.input_snapshot_id
    assert persisted.input_row_count == run.input_row_count
    assert persisted.included_count == run.included_count
    assert persisted.created_at == run.created_at

    fetched = candidate_pool_run_repository.get_by_id(run.id)
    assert fetched is not None
    assert fetched.id == run.id
    assert fetched.status == CandidatePoolStatus.CALCULATED


def test_duplicate_natural_key_raises_integrity_error(
    candidate_pool_run_repository: SqlAlchemyCandidatePoolRunRepository,
) -> None:
    """The ADR-0008 natural-key unique constraint rejects duplicates."""

    snapshot = uuid4()
    first = _new_calculated_run(
        trade_date=date(2026, 7, 31),
        algorithm_key="candidate_pool.v1",
        algorithm_version="v1.0",
        parameter_hash="a" * 64,
        input_snapshot_id=snapshot,
    )
    duplicate = _new_calculated_run(
        trade_date=date(2026, 7, 31),
        algorithm_key="candidate_pool.v1",
        algorithm_version="v1.0",
        parameter_hash="a" * 64,
        input_snapshot_id=snapshot,
    )

    candidate_pool_run_repository.add(first)
    with pytest.raises(IntegrityError):
        candidate_pool_run_repository.add(duplicate)


def test_get_by_natural_key_returns_persisted_run(
    candidate_pool_run_repository: SqlAlchemyCandidatePoolRunRepository,
) -> None:
    """``get_by_natural_key`` is the idempotent rerun lookup surface."""

    snapshot = uuid4()
    first = _new_calculated_run(
        trade_date=date(2026, 7, 31),
        algorithm_key="candidate_pool.v1",
        algorithm_version="v1.0",
        parameter_hash="a" * 64,
        input_snapshot_id=snapshot,
    )
    candidate_pool_run_repository.add(first)
    candidate_pool_run_repository.transition_status(
        first.id, CandidatePoolStatus.VALIDATED, at=_utc(2026, 7, 31, 10)
    )
    candidate_pool_run_repository.transition_status(
        first.id, CandidatePoolStatus.PUBLISHED, at=_utc(2026, 7, 31, 11)
    )

    fetched = candidate_pool_run_repository.get_by_natural_key(
        trade_date=date(2026, 7, 31),
        algorithm_key="candidate_pool.v1",
        algorithm_version="v1.0",
        parameter_hash="a" * 64,
        input_snapshot_id=snapshot,
    )

    assert fetched is not None
    assert fetched.id == first.id
    assert fetched.status == CandidatePoolStatus.PUBLISHED
    assert fetched.published_at == _utc(2026, 7, 31, 11)


def test_get_by_natural_key_returns_none_when_absent(
    candidate_pool_run_repository: SqlAlchemyCandidatePoolRunRepository,
) -> None:
    """A fresh trade date has no matching row yet."""

    fetched = candidate_pool_run_repository.get_by_natural_key(
        trade_date=date(2026, 7, 31),
        algorithm_key="candidate_pool.v1",
        algorithm_version="v1.0",
        parameter_hash="a" * 64,
        input_snapshot_id=uuid4(),
    )

    assert fetched is None


def test_transition_runs_full_lifecycle(
    candidate_pool_run_repository: SqlAlchemyCandidatePoolRunRepository,
) -> None:
    """A run walks CALCULATED -> VALIDATED -> PUBLISHED end-to-end."""

    run = _new_calculated_run()
    candidate_pool_run_repository.add(run)

    validated = candidate_pool_run_repository.transition_status(
        run.id, CandidatePoolStatus.VALIDATED, at=_utc(2026, 7, 31, 10)
    )
    assert validated.status == CandidatePoolStatus.VALIDATED
    assert validated.finished_at == _utc(2026, 7, 31, 10)

    published = candidate_pool_run_repository.transition_status(
        run.id, CandidatePoolStatus.PUBLISHED, at=_utc(2026, 7, 31, 11)
    )
    assert published.status == CandidatePoolStatus.PUBLISHED
    assert published.published_at == _utc(2026, 7, 31, 11)


def test_transition_to_rejected_requires_reason(
    candidate_pool_run_repository: SqlAlchemyCandidatePoolRunRepository,
) -> None:
    """The repository surfaces the domain invariant via ValueError."""

    run = _new_calculated_run()
    candidate_pool_run_repository.add(run)
    candidate_pool_run_repository.transition_status(
        run.id, CandidatePoolStatus.VALIDATED, at=_utc(2026, 7, 31, 10)
    )

    with pytest.raises(ValueError):
        candidate_pool_run_repository.transition_status(
            run.id,
            CandidatePoolStatus.REJECTED,
            at=_utc(2026, 7, 31, 11),
        )

    rejected = candidate_pool_run_repository.transition_status(
        run.id,
        CandidatePoolStatus.REJECTED,
        at=_utc(2026, 7, 31, 11),
        rejection_reason="coverage below threshold",
    )
    assert rejected.status == CandidatePoolStatus.REJECTED
    assert rejected.rejection_reason == "coverage below threshold"
    assert rejected.rejected_at == _utc(2026, 7, 31, 11)


def test_transition_illegal_skip_raises(
    candidate_pool_run_repository: SqlAlchemyCandidatePoolRunRepository,
) -> None:
    """The state machine rejects ``CALCULATED -> PUBLISHED``."""

    run = _new_calculated_run()
    candidate_pool_run_repository.add(run)

    with pytest.raises(ValueError):
        candidate_pool_run_repository.transition_status(
            run.id, CandidatePoolStatus.PUBLISHED, at=_utc(2026, 7, 31, 11)
        )


def test_transition_unknown_run_raises_lookup_error(
    candidate_pool_run_repository: SqlAlchemyCandidatePoolRunRepository,
) -> None:
    """An unknown run id surfaces as :class:`LookupError`."""

    with pytest.raises(LookupError):
        candidate_pool_run_repository.transition_status(
            uuid4(),
            CandidatePoolStatus.VALIDATED,
            at=_utc(2026, 7, 31, 10),
        )


def test_list_by_status_filters_runs(
    candidate_pool_run_repository: SqlAlchemyCandidatePoolRunRepository,
) -> None:
    """``list_by_status`` returns only runs in the requested status."""

    first = _new_calculated_run(trade_date=date(2026, 7, 31))
    second = _new_calculated_run(
        trade_date=date(2026, 7, 30),
        parameter_hash="b" * 64,
    )
    candidate_pool_run_repository.add(first)
    candidate_pool_run_repository.add(second)
    candidate_pool_run_repository.transition_status(
        first.id, CandidatePoolStatus.VALIDATED, at=_utc(2026, 7, 31, 10)
    )

    calculated = candidate_pool_run_repository.list_by_status(
        CandidatePoolStatus.CALCULATED
    )
    validated = candidate_pool_run_repository.list_by_status(
        CandidatePoolStatus.VALIDATED
    )

    assert [run.id for run in calculated] == [second.id]
    assert [run.id for run in validated] == [first.id]


def test_list_by_trade_date_returns_runs_for_date(
    candidate_pool_run_repository: SqlAlchemyCandidatePoolRunRepository,
) -> None:
    """``list_by_trade_date`` returns only runs for that trade date."""

    a = _new_calculated_run(trade_date=date(2026, 7, 31))
    b = _new_calculated_run(
        trade_date=date(2026, 7, 30),
        parameter_hash="b" * 64,
    )
    candidate_pool_run_repository.add(a)
    candidate_pool_run_repository.add(b)

    on_a = candidate_pool_run_repository.list_by_trade_date(date(2026, 7, 31))
    on_b = candidate_pool_run_repository.list_by_trade_date(date(2026, 7, 30))

    assert [run.id for run in on_a] == [a.id]
    assert [run.id for run in on_b] == [b.id]


def test_bulk_add_and_list_round_trip(
    candidate_pool_run_repository: SqlAlchemyCandidatePoolRunRepository,
    candidate_pool_item_repository: SqlAlchemyCandidatePoolItemRepository,
    db_session: Session,
) -> None:
    """Items round-trip through bulk_add + list_by_run_id with full JSONB fidelity."""

    run = _new_calculated_run(input_row_count=2, included_count=1)
    candidate_pool_run_repository.add(run)
    a = _insert_instrument(db_session, symbol="510050")
    b = _insert_instrument(db_session, symbol="510300")
    instrument_id_a = InstrumentId(a)
    instrument_id_b = InstrumentId(b)

    items = (
        CandidatePoolItem(
            instrument_id=instrument_id_a,
            included=True,
            rank=1,
            total_score=Decimal("0.91"),
            metrics={"liquidity": Decimal("1.5"), "stability": Decimal("0.7")},
            rule_results=(
                RuleOutcome(
                    rule_key="liquidity",
                    passed=True,
                    severity=RuleSeverity.INFO,
                    value=Decimal("1.5"),
                    threshold=Decimal("1.0"),
                ),
            ),
        ),
        CandidatePoolItem(
            instrument_id=instrument_id_b,
            included=False,
            rank=None,
            total_score=None,
            metrics={},
            exclusion_reasons=(
                ExclusionReason(code="suspended", message="paused"),
            ),
        ),
    )

    inserted = candidate_pool_item_repository.bulk_add(run.id, items)
    assert inserted == 2

    persisted = candidate_pool_item_repository.list_by_run_id(run.id)
    assert len(persisted) == 2

    included = next(item for item in persisted if item.included)
    excluded = next(item for item in persisted if not item.included)

    assert included.instrument_id == instrument_id_a
    assert included.rank == 1
    assert included.total_score == Decimal("0.91")
    assert included.metrics["liquidity"] == Decimal("1.5")
    assert included.metrics["stability"] == Decimal("0.7")
    assert len(included.rule_results) == 1
    assert included.rule_results[0].rule_key == "liquidity"
    assert included.rule_results[0].severity == RuleSeverity.INFO
    assert included.rule_results[0].value == Decimal("1.5")

    assert excluded.instrument_id == instrument_id_b
    assert excluded.rank is None
    assert excluded.total_score is None
    assert len(excluded.exclusion_reasons) == 1
    assert excluded.exclusion_reasons[0].code == "suspended"
    assert excluded.exclusion_reasons[0].message == "paused"


def test_bulk_add_duplicate_instrument_raises(
    candidate_pool_run_repository: SqlAlchemyCandidatePoolRunRepository,
    candidate_pool_item_repository: SqlAlchemyCandidatePoolItemRepository,
    db_session: Session,
) -> None:
    """The composite primary key rejects duplicate ``(run_id, instrument_id)``."""

    run = _new_calculated_run()
    candidate_pool_run_repository.add(run)
    instrument_id = InstrumentId(_insert_instrument(db_session, symbol="510050"))

    items = (
        CandidatePoolItem(
            instrument_id=instrument_id,
            included=True,
            rank=1,
            total_score=Decimal("0.5"),
            metrics={},
        ),
        CandidatePoolItem(
            instrument_id=instrument_id,
            included=False,
            rank=None,
            total_score=None,
            metrics={},
            exclusion_reasons=(
                ExclusionReason(code="suspended", message="paused"),
            ),
        ),
    )

    with pytest.raises(IntegrityError):
        candidate_pool_item_repository.bulk_add(run.id, items)


if __name__ == "__main__":
    import unittest

    unittest.main()