/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/candidate-pool/latest": {
    /**
     * Get Latest Candidate Pool
     * @description Return the most recently published candidate-pool run.
     */
    get: operations["get_latest_candidate_pool_api_v1_candidate_pool_latest_get"];
  };
  "/api/v1/candidate-pool/latest/diff": {
    /**
     * Get Latest Candidate Pool Diff
     * @description Diff the latest published run against the previous earlier published run.
     */
    get: operations["get_latest_candidate_pool_diff_api_v1_candidate_pool_latest_diff_get"];
  };
  "/api/v1/candidate-pool/{run_id}/diff": {
    /**
     * Get Candidate Pool Diff
     * @description Diff the published run identified by ``run_id`` against its predecessor.
     *
     * Returns 404 when ``run_id`` does not exist or the run is not in the
     * ``PUBLISHED`` state; the diff itself is read-only and never mutates
     * storage state.
     */
    get: operations["get_candidate_pool_diff_api_v1_candidate_pool__run_id__diff_get"];
  };
  "/api/v1/data-freshness": {
    /**
     * Get Data Freshness
     * @description Return the data-freshness summary for ``expected_trade_date``.
     */
    get: operations["get_data_freshness_api_v1_data_freshness_get"];
  };
  "/api/v1/etf/daily-bars": {
    /**
     * List Etf Daily Bars
     * @description Return the latest revision per trade_date for one instrument.
     */
    get: operations["list_etf_daily_bars_api_v1_etf_daily_bars_get"];
  };
  "/api/v1/etf/instruments": {
    /**
     * List Etf Instruments
     * @description Return the active ETF master data, optionally filtered by exchange/status.
     */
    get: operations["list_etf_instruments_api_v1_etf_instruments_get"];
  };
  "/api/v1/pipeline-runs": {
    /**
     * List Pipeline Runs
     * @description Return a paginated history of ``personal_etf_daily_job`` runs.
     *
     * The repository applies the ``job_key`` filter, limit and offset in SQL,
     * and its dedicated count query supplies the exact total. ``SQLAlchemyError``
     * is caught and re-raised as a sanitized HTTP 500 so a connection string or
     * driver detail never leaks to the client.
     */
    get: operations["list_pipeline_runs_api_v1_pipeline_runs_get"];
  };
  "/api/v1/pipeline-runs/latest": {
    /**
     * Get Latest Pipeline Run
     * @description Return the most recent run of the personal daily job.
     *
     * Walks :meth:`SqlAlchemyPipelineRunRepository.list_recent` - which is
     * ordered by ``started_at`` descending - and returns the first run
     * matching ``job_key = "personal_etf_daily_job"``. Returns ``404`` when
     * no matching run exists; any run that resolves to a different job_key
     * is intentionally ignored.
     */
    get: operations["get_latest_pipeline_run_api_v1_pipeline_runs_latest_get"];
  };
  "/api/v1/pipeline-runs/{run_id}": {
    /**
     * Get Pipeline Run By Id
     * @description Return the run for ``run_id`` if it belongs to the personal daily job.
     *
     * A missing run OR a run that resolves to a different ``job_key`` both
     * surface as ``404``; the front-end cannot distinguish between "the
     * UUID does not exist" and "the UUID belongs to a different job", which
     * matches the contract spelled out in PR-03 §3.2.
     */
    get: operations["get_pipeline_run_by_id_api_v1_pipeline_runs__run_id__get"];
  };
  "/health": {
    /** Health */
    get: operations["health_health_get"];
  };
  "/v1/instruments": {
    /** List Instruments */
    get: operations["list_instruments_v1_instruments_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * CandidatePoolDiffEntry
     * @description One instrument entry in a candidate-pool diff bucket.
     *
     * Carries the raw ``instrument_id`` plus the resolved display fields
     * so the Web can render the diff without making a follow-up Instrument
     * lookup. ``symbol`` / ``name`` / ``exchange`` are ``None`` when the
     * instrument row is missing; ordering is deterministic - ``symbol``
     * ascending with ``instrument_id`` as the tiebreaker.
     */
    CandidatePoolDiffEntry: {
      /** Exchange */
      exchange?: string | null;
      /**
       * Instrument Id
       * Format: uuid
       */
      instrument_id: string;
      /** Name */
      name?: string | null;
      /** Symbol */
      symbol?: string | null;
    };
    /**
     * CandidatePoolDiffResponse
     * @description Response envelope for the candidate-pool diff endpoints.
     *
     * Compares the set of ``included=True`` instruments in the current
     * published run against the most recent earlier published run.
     * ``added`` is the set of instruments that appear only in the current
     * run, ``retained`` is the intersection, and ``removed`` is the set
     * that appear only in the previous run. Excluded items (where
     * ``included=False``) are NEVER reported in any bucket - the diff
     * reflects candidate-pool membership changes, not input-pool changes.
     * When no earlier published run exists, ``previous_trade_date`` is
     * ``None`` and every included instrument in the current run is
     * reported as ``added`` with ``retained`` and ``removed`` both empty.
     */
    CandidatePoolDiffResponse: {
      /** Added */
      added?: components["schemas"]["CandidatePoolDiffEntry"][];
      /** Previous Trade Date */
      previous_trade_date?: string | null;
      /** Removed */
      removed?: components["schemas"]["CandidatePoolDiffEntry"][];
      /** Retained */
      retained?: components["schemas"]["CandidatePoolDiffEntry"][];
      /**
       * Trade Date
       * Format: date
       */
      trade_date: string;
    };
    /**
     * CandidatePoolItemResponse
     * @description One per-instrument judgment from the latest published pool.
     */
    CandidatePoolItemResponse: {
      /** Exchange */
      exchange?: string | null;
      /** Exclusion Reasons */
      exclusion_reasons?: components["schemas"]["ExclusionReasonResponse"][];
      /** Included */
      included: boolean;
      /**
       * Instrument Id
       * Format: uuid
       */
      instrument_id: string;
      /** Metrics */
      metrics?: {
        [key: string]: string;
      };
      /** Name */
      name?: string | null;
      /** Rank */
      rank?: number | null;
      /** Rule Results */
      rule_results?: components["schemas"]["RuleOutcomeResponse"][];
      /** Symbol */
      symbol?: string | null;
      /** Total Score */
      total_score?: string | null;
    };
    /**
     * CandidatePoolLatestResponse
     * @description Response envelope for the ``GET /api/v1/candidate-pool/latest`` endpoint.
     */
    CandidatePoolLatestResponse: {
      /** Algorithm Key */
      algorithm_key: string;
      /** Algorithm Version */
      algorithm_version: string;
      /** Content Hash */
      content_hash: string;
      /** Excluded Count */
      excluded_count: number;
      /** Included Count */
      included_count: number;
      /** Items */
      items: components["schemas"]["CandidatePoolItemResponse"][];
      /** Parameter Set Key */
      parameter_set_key: string;
      /** Published At */
      published_at?: string | null;
      /** Row Count */
      row_count: number;
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /**
       * Snapshot Id
       * Format: uuid
       */
      snapshot_id: string;
      /**
       * Trade Date
       * Format: date
       */
      trade_date: string;
    };
    /**
     * DailyBarListResponse
     * @description Paginated envelope for the ``GET /api/v1/etf/daily-bars`` endpoint.
     */
    DailyBarListResponse: {
      /** Items */
      items: components["schemas"]["DailyBarResponse"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /**
     * DailyBarResponse
     * @description One row of standardized daily OHLCV data (ADR-0005 / ADR-0006).
     */
    DailyBarResponse: {
      /** Adjustment */
      adjustment: string;
      /** Amount */
      amount: string | null;
      /** Close */
      close: string | null;
      /** High */
      high: string | null;
      /**
       * Instrument Id
       * Format: uuid
       */
      instrument_id: string;
      /** Low */
      low: string | null;
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string;
      /** Open */
      open: string | null;
      /** Prev Close */
      prev_close: string | null;
      /** Revision */
      revision: number;
      /** Source Batch Id */
      source_batch_id: string | null;
      /** Source Provider */
      source_provider: string;
      /**
       * Trade Date
       * Format: date
       */
      trade_date: string;
      /** Trading Status */
      trading_status: string;
      /** Volume */
      volume: string | null;
    };
    /**
     * DataFreshnessResponse
     * @description Response envelope for the ``GET /api/v1/data-freshness`` endpoint.
     *
     * ``status`` follows the same vocabulary the front-end uses for the
     * personal daily-job banner. ``missing_count`` is the gap between the
     * active instrument universe and the daily bars observed for
     * ``expected_trade_date``; it is always
     * ``max(0, universe_count - daily_bar_count)`` regardless of the
     * high-level ``status`` so the UI can surface a progress bar.
     */
    DataFreshnessResponse: {
      /**
       * As Of
       * Format: date-time
       */
      as_of: string;
      /** Candidate Count */
      candidate_count: number;
      /** Daily Bar Count */
      daily_bar_count: number;
      /** Latest Published Trade Date */
      latest_published_trade_date?: string | null;
      /** Missing Count */
      missing_count: number;
      /** Pipeline Run Id */
      pipeline_run_id?: string | null;
      /** Pipeline Status */
      pipeline_status?: string | null;
      /** Snapshot Id */
      snapshot_id?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: "fresh" | "partial" | "stale" | "missing" | "failed";
      /** Universe Count */
      universe_count: number;
    };
    /**
     * ExclusionReasonResponse
     * @description Machine-readable reason an instrument was excluded.
     */
    ExclusionReasonResponse: {
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Service */
      service: string;
      /** Status */
      status: string;
    };
    /**
     * InstrumentListResponse
     * @description Paginated envelope for the ``GET /api/v1/etf/instruments`` endpoint.
     */
    InstrumentListResponse: {
      /** Items */
      items: components["schemas"]["InstrumentResponse"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /**
     * InstrumentResponse
     * @description Public representation of one ``core.instruments`` row.
     */
    InstrumentResponse: {
      /** Category */
      category?: string | null;
      /** Currency */
      currency: string;
      /** Delist Date */
      delist_date?: string | null;
      /** Exchange */
      exchange: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Instrument Type */
      instrument_type: string;
      /** Is Active */
      is_active: boolean;
      /** List Date */
      list_date?: string | null;
      /** Name */
      name: string;
      /** Status */
      status: string;
      /** Symbol */
      symbol: string;
      /** Underlying Index */
      underlying_index?: string | null;
    };
    /**
     * PipelineRunListResponse
     * @description Paginated envelope for the ``GET /api/v1/pipeline-runs`` endpoint.
     *
     * ``total`` counts every ``personal_etf_daily_job`` run (i.e. it is
     * computed independently of ``limit`` / ``offset``) so the UI can
     * render the page count without an extra round trip. ``items`` is
     * always ordered by ``started_at`` descending and then ``id``
     * ascending so successive pages are stable.
     */
    PipelineRunListResponse: {
      /** Items */
      items: components["schemas"]["PipelineRunResponse"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /**
     * PipelineRunResponse
     * @description Public representation of one ``ops.pipeline_runs`` row.
     *
     * Mirrors the storage/domain :class:`invest_domain.pipeline.PipelineRun`
     * fields that PR-03 needs on the read path; storage-internal handles
     * (``dagster_run_id``, ``algorithm_version``, ``config_snapshot``,
     * ``created_at``, ``updated_at``) are deliberately omitted.
     */
    PipelineRunResponse: {
      /** Error Code */
      error_code?: string | null;
      /** Error Summary */
      error_summary?: string | null;
      /** Finished At */
      finished_at?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Job Key */
      job_key: string;
      /** Partition Key */
      partition_key?: string | null;
      /** Started At */
      started_at?: string | null;
      /** Status */
      status: string;
      /** Trigger Type */
      trigger_type: string;
    };
    /**
     * RuleOutcomeResponse
     * @description Outcome of one rule applied to one instrument in a pool.
     */
    RuleOutcomeResponse: {
      /** Message */
      message?: string | null;
      /** Passed */
      passed: boolean;
      /** Rule Key */
      rule_key: string;
      /** Severity */
      severity: string;
      /** Threshold */
      threshold?: string | null;
      /** Value */
      value?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get Latest Candidate Pool
   * @description Return the most recently published candidate-pool run.
   */
  get_latest_candidate_pool_api_v1_candidate_pool_latest_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CandidatePoolLatestResponse"];
        };
      };
    };
  };
  /**
   * Get Latest Candidate Pool Diff
   * @description Diff the latest published run against the previous earlier published run.
   */
  get_latest_candidate_pool_diff_api_v1_candidate_pool_latest_diff_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CandidatePoolDiffResponse"];
        };
      };
    };
  };
  /**
   * Get Candidate Pool Diff
   * @description Diff the published run identified by ``run_id`` against its predecessor.
   *
   * Returns 404 when ``run_id`` does not exist or the run is not in the
   * ``PUBLISHED`` state; the diff itself is read-only and never mutates
   * storage state.
   */
  get_candidate_pool_diff_api_v1_candidate_pool__run_id__diff_get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CandidatePoolDiffResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Data Freshness
   * @description Return the data-freshness summary for ``expected_trade_date``.
   */
  get_data_freshness_api_v1_data_freshness_get: {
    parameters: {
      query?: {
        expected_trade_date?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DataFreshnessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Etf Daily Bars
   * @description Return the latest revision per trade_date for one instrument.
   */
  list_etf_daily_bars_api_v1_etf_daily_bars_get: {
    parameters: {
      query: {
        instrument_id: string;
        start_date: string;
        end_date: string;
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DailyBarListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Etf Instruments
   * @description Return the active ETF master data, optionally filtered by exchange/status.
   */
  list_etf_instruments_api_v1_etf_instruments_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        exchange?: string | null;
        status?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InstrumentListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Pipeline Runs
   * @description Return a paginated history of ``personal_etf_daily_job`` runs.
   *
   * The repository applies the ``job_key`` filter, limit and offset in SQL,
   * and its dedicated count query supplies the exact total. ``SQLAlchemyError``
   * is caught and re-raised as a sanitized HTTP 500 so a connection string or
   * driver detail never leaks to the client.
   */
  list_pipeline_runs_api_v1_pipeline_runs_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PipelineRunListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Latest Pipeline Run
   * @description Return the most recent run of the personal daily job.
   *
   * Walks :meth:`SqlAlchemyPipelineRunRepository.list_recent` - which is
   * ordered by ``started_at`` descending - and returns the first run
   * matching ``job_key = "personal_etf_daily_job"``. Returns ``404`` when
   * no matching run exists; any run that resolves to a different job_key
   * is intentionally ignored.
   */
  get_latest_pipeline_run_api_v1_pipeline_runs_latest_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PipelineRunResponse"];
        };
      };
    };
  };
  /**
   * Get Pipeline Run By Id
   * @description Return the run for ``run_id`` if it belongs to the personal daily job.
   *
   * A missing run OR a run that resolves to a different ``job_key`` both
   * surface as ``404``; the front-end cannot distinguish between "the
   * UUID does not exist" and "the UUID belongs to a different job", which
   * matches the contract spelled out in PR-03 §3.2.
   */
  get_pipeline_run_by_id_api_v1_pipeline_runs__run_id__get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PipelineRunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /** List Instruments */
  list_instruments_v1_instruments_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InstrumentListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
