/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/candidate-pool/latest": {
    /**
     * Get Latest Candidate Pool
     * @description Return the most recently published candidate-pool run.
     */
    get: operations["get_latest_candidate_pool_api_v1_candidate_pool_latest_get"];
  };
  "/api/v1/candidate-pool/latest/diff": {
    /**
     * Get Latest Candidate Pool Diff
     * @description Diff the latest published run against the previous earlier published run.
     */
    get: operations["get_latest_candidate_pool_diff_api_v1_candidate_pool_latest_diff_get"];
  };
  "/api/v1/candidate-pool/{run_id}/diff": {
    /**
     * Get Candidate Pool Diff
     * @description Diff the published run identified by ``run_id`` against its predecessor.
     *
     * Returns 404 when ``run_id`` does not exist or the run is not in the
     * ``PUBLISHED`` state; the diff itself is read-only and never mutates
     * storage state.
     */
    get: operations["get_candidate_pool_diff_api_v1_candidate_pool__run_id__diff_get"];
  };
  "/api/v1/data-freshness": {
    /**
     * Get Data Freshness
     * @description Return the data-freshness summary for ``expected_trade_date``.
     *
     * The application service applies the ``expected_trade_date`` default
     * (latest weekday from :func:`invest_api.clock.market_today`), runs
     * the snapshot / published / empty fallback chain and the
     * status-state-machine reduction, and packages the outcome into a
     * small :class:`DataFreshnessView` dataclass. The router only maps
     * that view onto the public Pydantic response shape and converts
     * :class:`DataFreshnessQueryError` into a sanitized HTTP 500.
     */
    get: operations["get_data_freshness_api_v1_data_freshness_get"];
  };
  "/api/v1/etf/daily-bars": {
    /**
     * List Etf Daily Bars
     * @description Return the latest revision per trade_date for one instrument.
     */
    get: operations["list_etf_daily_bars_api_v1_etf_daily_bars_get"];
  };
  "/api/v1/etf/instruments": {
    /**
     * List Etf Instruments
     * @description Return the active ETF master data, optionally filtered by exchange/status.
     */
    get: operations["list_etf_instruments_api_v1_etf_instruments_get"];
  };
  "/api/v1/external-observations/{observation_id}/admission-decisions": {
    /** Decide Admission */
    post: operations["decide_admission_api_v1_external_observations__observation_id__admission_decisions_post"];
  };
  "/api/v1/external-workflows": {
    /** List External Workflows */
    get: operations["list_external_workflows_api_v1_external_workflows_get"];
  };
  "/api/v1/external-workflows/{run_id}": {
    /** Get External Workflow */
    get: operations["get_external_workflow_api_v1_external_workflows__run_id__get"];
  };
  "/api/v1/external-workflows/{run_id}/artifacts": {
    /** List External Artifacts */
    get: operations["list_external_artifacts_api_v1_external_workflows__run_id__artifacts_get"];
  };
  "/api/v1/external-workflows/{run_id}/observations": {
    /** List External Observations */
    get: operations["list_external_observations_api_v1_external_workflows__run_id__observations_get"];
  };
  "/api/v1/integration/artifacts/{artifact_id}": {
    /** Preview Artifact */
    get: operations["preview_artifact_api_v1_integration_artifacts__artifact_id__get"];
  };
  "/api/v1/integration/health": {
    /** Get Integration Health */
    get: operations["get_integration_health_api_v1_integration_health_get"];
  };
  "/api/v1/market-breadth/latest": {
    /**
     * Get Latest Market Breadth
     * @description Return the latest Market Breadth snapshot for ``as_of_date``.
     *
     * ``as_of_date`` is optional: omitting it asks the service for the
     * newest snapshot regardless of trade date; supplying a value
     * narrows the lookup to that exact date. The application service
     * pins ``scope_type`` / ``scope_key`` so the route never reads a
     * sibling ``scope_type`` family (e.g. ``market_temperature``)
     * through the breadth surface.
     */
    get: operations["get_latest_market_breadth_api_v1_market_breadth_latest_get"];
  };
  "/api/v1/market-temperature/latest": {
    /** Get Latest Market Temperature */
    get: operations["get_latest_market_temperature_api_v1_market_temperature_latest_get"];
  };
  "/api/v1/opportunity-radar": {
    /** List Opportunity Radar */
    get: operations["list_opportunity_radar_api_v1_opportunity_radar_get"];
  };
  "/api/v1/pipeline-runs": {
    /**
     * List Pipeline Runs
     * @description Return a paginated history of ``personal_etf_daily_job`` runs.
     *
     * The application service applies the ``job_key`` filter, limit and
     * offset in SQL and supplies the exact total from its companion
     * count query. ``PipelineRunQueryError`` (raised when the underlying
     * repository raises ``SQLAlchemyError``) is caught and re-raised as a
     * sanitized HTTP 500.
     */
    get: operations["list_pipeline_runs_api_v1_pipeline_runs_get"];
  };
  "/api/v1/pipeline-runs/latest": {
    /**
     * Get Latest Pipeline Run
     * @description Return the most recent run of the personal daily job.
     *
     * The application service walks the repository's ``list_recent``
     * page - ordered by ``started_at`` descending - and returns the first
     * run matching ``job_key = "personal_etf_daily_job"``. The router
     * surfaces ``404`` when no matching run exists; any run that resolves
     * to a different ``job_key`` is intentionally ignored.
     */
    get: operations["get_latest_pipeline_run_api_v1_pipeline_runs_latest_get"];
  };
  "/api/v1/pipeline-runs/{run_id}": {
    /**
     * Get Pipeline Run By Id
     * @description Return the run for ``run_id`` if it belongs to the personal daily job.
     *
     * A missing run OR a run that resolves to a different ``job_key`` both
     * surface as ``404``; the front-end cannot distinguish between "the
     * UUID does not exist" and "the UUID belongs to a different job".
     */
    get: operations["get_pipeline_run_by_id_api_v1_pipeline_runs__run_id__get"];
  };
  "/api/v1/research-cases": {
    /** List Research Cases */
    get: operations["list_research_cases_api_v1_research_cases_get"];
  };
  "/api/v1/research-cases/from-external-observations/{observation_id}": {
    /** Create Case From Observation */
    post: operations["create_case_from_observation_api_v1_research_cases_from_external_observations__observation_id__post"];
  };
  "/api/v1/research-cases/{case_id}": {
    /** Get Research Case */
    get: operations["get_research_case_api_v1_research_cases__case_id__get"];
  };
  "/api/v1/research-cases/{case_id}/evidence": {
    /** Get Research Case Evidence */
    get: operations["get_research_case_evidence_api_v1_research_cases__case_id__evidence_get"];
  };
  "/api/v1/research-cases/{case_id}/external-observations/{observation_id}/evidence": {
    /** Link External Observation */
    post: operations["link_external_observation_api_v1_research_cases__case_id__external_observations__observation_id__evidence_post"];
  };
  "/api/v1/research-cases/{case_id}/runs": {
    /** Queue Research Run */
    post: operations["queue_research_run_api_v1_research_cases__case_id__runs_post"];
  };
  "/api/v1/research-cases/{case_id}/workspace": {
    /**
     * Get Research Case Workspace
     * @description Return the read-only case workspace envelope (PR-W05 first increment).
     *
     * The endpoint composes the existing
     * ``ResearchCaseResponse`` / ``EvidencePackResponse`` /
     * ``ResearchRunResponse`` / ``ResearchResultResponse`` resource
     * shapes; no new resource field is invented. ``results`` is the
     * positional, parallel companion of ``runs`` so the front-end can
     * pair them by index; a ``null`` result slot is exposed for runs
     * that have not (yet) published a result rather than fabricating
     * one. The endpoint is the read-only API contract for the future
     * workspace page; the front-end itself is not part of this PR.
     *
     * Errors:
     *
     * - ``404`` when the case does not exist (the same detail string
     *   as ``GET /api/v1/research-cases/{case_id}`` so callers can
     *   share error handlers).
     * - ``500`` with the sanitized ``"Research query failed"`` detail
     *   on :class:`ResearchQueryError`, consistent with the existing
     *   endpoints.
     * - ``422`` for a malformed ``case_id`` UUID (FastAPI default).
     */
    get: operations["get_research_case_workspace_api_v1_research_cases__case_id__workspace_get"];
  };
  "/api/v1/research-center": {
    /**
     * Get Research Center
     * @description Return the Slice 1 Research Center contract response.
     *
     * The handler owns a single UTC wall-clock value and reuses it for
     * both ``generated_at`` and ``market.data_freshness.checked_at`` so
     * the two timestamps are always identical. The application service
     * converts the two underlying sources' controlled errors into
     * explicit failed sub-segments before this router sees them; any
     * other exception is intentionally allowed to propagate so FastAPI's
     * generic error boundary (and not this router) sanitises the
     * response. The endpoint is intentionally GET-only — no POST, PUT,
     * PATCH or DELETE handlers exist on this router and the OpenAPI
     * spec reflects that.
     */
    get: operations["get_research_center_api_v1_research_center_get"];
  };
  "/api/v1/research-dashboard": {
    /**
     * Get Research Dashboard
     * @description Return the read-only Research Cockpit dashboard aggregate.
     *
     * The dashboard derives every field from the existing PR-7
     * resource-level readers (``ResearchCaseReader`` /
     * ``ResearchRunReader`` / ``ResearchEvidenceReader``). The
     * application service owns the orchestration, the deterministic
     * ordering, the bounded ``recent_runs`` list and the
     * ``SQLAlchemyError`` boundary; this router is intentionally a
     * thin pass-through that stamps ``generated_at`` with a UTC
     * wall-clock value so two callers hitting the service in the
     * same instant still observe distinct response timestamps.
     *
     * ``market_status`` is always the explicit
     * ``{"state": "unavailable", "reason": "..."}`` shape until a
     * market dashboard source is registered; no market / factor
     * values or investment conclusions are invented on this path.
     */
    get: operations["get_research_dashboard_api_v1_research_dashboard_get"];
  };
  "/api/v1/research-runs": {
    /** List Research Runs */
    get: operations["list_research_runs_api_v1_research_runs_get"];
  };
  "/api/v1/research-runs/{run_id}": {
    /** Get Research Run */
    get: operations["get_research_run_api_v1_research_runs__run_id__get"];
  };
  "/api/v1/research-runs/{run_id}/result": {
    /** Get Research Run Result */
    get: operations["get_research_run_result_api_v1_research_runs__run_id__result_get"];
  };
  "/health": {
    /** Health */
    get: operations["health_health_get"];
  };
  "/v1/instruments": {
    /** List Instruments */
    get: operations["list_instruments_v1_instruments_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AdmissionDecisionRequest */
    AdmissionDecisionRequest: {
      /**
       * Conflict Detected
       * @default false
       */
      conflict_detected?: boolean;
      /**
       * Decided By
       * @default api
       */
      decided_by?: string;
      /** Freshness Ok */
      freshness_ok: boolean;
      /** Idempotency Key */
      idempotency_key: string;
      /** Identity Ok */
      identity_ok: boolean;
      /** Internal Cross Check Ok */
      internal_cross_check_ok?: boolean | null;
      /** Reason */
      reason?: string | null;
      /**
       * Rules Version
       * @default observation-admission/1.0
       */
      rules_version?: string;
      /** Unit Ok */
      unit_ok: boolean;
    };
    /** AdmissionDecisionResponse */
    AdmissionDecisionResponse: {
      /** Admission Status */
      admission_status: string;
      /** Idempotent */
      idempotent: boolean;
      /**
       * Observation Id
       * Format: uuid
       */
      observation_id: string;
      /** Reason */
      reason: string;
    };
    /** ArtifactPreviewResponse */
    ArtifactPreviewResponse: {
      /**
       * Artifact Id
       * Format: uuid
       */
      artifact_id: string;
      /** Content Hash */
      content_hash: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Logical Uri */
      logical_uri: string;
      /** Media Type */
      media_type: string;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      };
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /** Size Bytes */
      size_bytes: number;
    };
    /**
     * CandidatePoolDiffEntry
     * @description One instrument entry in a candidate-pool diff bucket.
     *
     * Carries the raw ``instrument_id`` plus the resolved display fields
     * so the Web can render the diff without making a follow-up Instrument
     * lookup. ``symbol`` / ``name`` / ``exchange`` are ``None`` when the
     * instrument row is missing; ordering is deterministic - ``symbol``
     * ascending with ``instrument_id`` as the tiebreaker.
     */
    CandidatePoolDiffEntry: {
      /** Exchange */
      exchange?: string | null;
      /**
       * Instrument Id
       * Format: uuid
       */
      instrument_id: string;
      /** Name */
      name?: string | null;
      /** Symbol */
      symbol?: string | null;
    };
    /**
     * CandidatePoolDiffResponse
     * @description Response envelope for the candidate-pool diff endpoints.
     *
     * Compares the set of ``included=True`` instruments in the current
     * published run against the most recent earlier published run.
     * ``added`` is the set of instruments that appear only in the current
     * run, ``retained`` is the intersection, and ``removed`` is the set
     * that appear only in the previous run. Excluded items (where
     * ``included=False``) are NEVER reported in any bucket - the diff
     * reflects candidate-pool membership changes, not input-pool changes.
     * When no earlier published run exists, ``previous_trade_date`` is
     * ``None`` and every included instrument in the current run is
     * reported as ``added`` with ``retained`` and ``removed`` both empty.
     */
    CandidatePoolDiffResponse: {
      /** Added */
      added?: components["schemas"]["CandidatePoolDiffEntry"][];
      /** Previous Trade Date */
      previous_trade_date?: string | null;
      /** Removed */
      removed?: components["schemas"]["CandidatePoolDiffEntry"][];
      /** Retained */
      retained?: components["schemas"]["CandidatePoolDiffEntry"][];
      /**
       * Trade Date
       * Format: date
       */
      trade_date: string;
    };
    /**
     * CandidatePoolItemResponse
     * @description One per-instrument judgment from the latest published pool.
     */
    CandidatePoolItemResponse: {
      /** Exchange */
      exchange?: string | null;
      /** Exclusion Reasons */
      exclusion_reasons?: components["schemas"]["ExclusionReasonResponse"][];
      /** Included */
      included: boolean;
      /**
       * Instrument Id
       * Format: uuid
       */
      instrument_id: string;
      /** Metrics */
      metrics?: {
        [key: string]: string;
      };
      /** Name */
      name?: string | null;
      /** Rank */
      rank?: number | null;
      /** Rule Results */
      rule_results?: components["schemas"]["RuleOutcomeResponse"][];
      /** Symbol */
      symbol?: string | null;
      /** Total Score */
      total_score?: string | null;
    };
    /**
     * CandidatePoolLatestResponse
     * @description Response envelope for the ``GET /api/v1/candidate-pool/latest`` endpoint.
     */
    CandidatePoolLatestResponse: {
      /** Algorithm Key */
      algorithm_key: string;
      /** Algorithm Version */
      algorithm_version: string;
      /** Content Hash */
      content_hash: string;
      /** Excluded Count */
      excluded_count: number;
      /** Included Count */
      included_count: number;
      /** Items */
      items: components["schemas"]["CandidatePoolItemResponse"][];
      /** Parameter Set Key */
      parameter_set_key: string;
      /** Published At */
      published_at?: string | null;
      /** Row Count */
      row_count: number;
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /**
       * Snapshot Id
       * Format: uuid
       */
      snapshot_id: string;
      /**
       * Trade Date
       * Format: date
       */
      trade_date: string;
    };
    /**
     * DailyBarListResponse
     * @description Paginated envelope for the ``GET /api/v1/etf/daily-bars`` endpoint.
     */
    DailyBarListResponse: {
      /** Items */
      items: components["schemas"]["DailyBarResponse"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /**
     * DailyBarResponse
     * @description One row of standardized daily OHLCV data (ADR-0005 / ADR-0006).
     */
    DailyBarResponse: {
      /** Adjustment */
      adjustment: string;
      /** Amount */
      amount: string | null;
      /** Close */
      close: string | null;
      /** High */
      high: string | null;
      /**
       * Instrument Id
       * Format: uuid
       */
      instrument_id: string;
      /** Low */
      low: string | null;
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string;
      /** Open */
      open: string | null;
      /** Prev Close */
      prev_close: string | null;
      /** Revision */
      revision: number;
      /** Source Batch Id */
      source_batch_id: string | null;
      /** Source Provider */
      source_provider: string;
      /**
       * Trade Date
       * Format: date
       */
      trade_date: string;
      /** Trading Status */
      trading_status: string;
      /** Volume */
      volume: string | null;
    };
    /**
     * DataFreshnessResponse
     * @description Response envelope for the ``GET /api/v1/data-freshness`` endpoint.
     *
     * ``status`` follows the same vocabulary the front-end uses for the
     * personal daily-job banner. ``missing_count`` is the gap between the
     * active instrument universe and the daily bars observed for
     * ``expected_trade_date``; it is always
     * ``max(0, universe_count - daily_bar_count)`` regardless of the
     * high-level ``status`` so the UI can surface a progress bar.
     */
    DataFreshnessResponse: {
      /**
       * As Of
       * Format: date-time
       */
      as_of: string;
      /** Candidate Count */
      candidate_count: number;
      /** Daily Bar Count */
      daily_bar_count: number;
      /** Latest Published Trade Date */
      latest_published_trade_date?: string | null;
      /** Missing Count */
      missing_count: number;
      /** Pipeline Run Id */
      pipeline_run_id?: string | null;
      /** Pipeline Status */
      pipeline_status?: string | null;
      /** Snapshot Id */
      snapshot_id?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: "fresh" | "partial" | "stale" | "missing" | "failed";
      /** Universe Count */
      universe_count: number;
    };
    /** EvidenceCaseResponse */
    EvidenceCaseResponse: {
      /**
       * As Of Date
       * Format: date
       */
      as_of_date: string;
      /** Case Id */
      case_id?: string | null;
      /** Horizon */
      horizon: string;
      /**
       * Instrument Id
       * Format: uuid
       */
      instrument_id: string;
      /** Question */
      question: string;
    };
    /** EvidenceDataQualityResponse */
    EvidenceDataQualityResponse: {
      /** Conflict Detected */
      conflict_detected: boolean;
      /** Freshness Status */
      freshness_status: string;
      /** Invalid Days */
      invalid_days: number;
      /** Observed Trading Days */
      observed_trading_days: number;
      /** Quality Status */
      quality_status: string;
      /** Suspended Days */
      suspended_days: number;
      /** Target Trading Days */
      target_trading_days: number;
      /** Valid Price Days */
      valid_price_days: number;
    };
    /** EvidenceFactorResponse */
    EvidenceFactorResponse: {
      /** Evidence Id */
      evidence_id: string | null;
      /** Factor Key */
      factor_key: string;
      /**
       * Observed Date
       * Format: date
       */
      observed_date: string;
      /** Quality Status */
      quality_status: string;
      /** Source Kind */
      source_kind: string;
      /** Source Ref */
      source_ref: string;
      /**
       * Unit
       * @description Measurement unit supplied by the frozen factor contract; interpret value using this field without percentage or currency rescaling.
       */
      unit: string;
      /** Value */
      value: string | null;
      /** Window */
      window: number;
    };
    /** EvidenceInstrumentResponse */
    EvidenceInstrumentResponse: {
      /** Currency */
      currency: string;
      /** Exchange */
      exchange: string;
      /**
       * Instrument Id
       * Format: uuid
       */
      instrument_id: string;
      /** Name */
      name: string;
      /** Symbol */
      symbol: string;
    };
    /** EvidenceMarketSnapshotResponse */
    EvidenceMarketSnapshotResponse: {
      /** Currency */
      currency: string;
      /** Latest Close */
      latest_close: string | null;
      /** Latest Trade Date */
      latest_trade_date: string | null;
      /** Observed Trading Days */
      observed_trading_days: number;
      /** Suspended Days */
      suspended_days: number;
      /** Valid Price Days */
      valid_price_days: number;
    };
    /** EvidencePackResponse */
    EvidencePackResponse: {
      case: components["schemas"]["EvidenceCaseResponse"];
      data_quality: components["schemas"]["EvidenceDataQualityResponse"];
      /** Factor Set Key */
      factor_set_key: string;
      /** Factor Set Version */
      factor_set_version: string;
      /** Factors */
      factors: components["schemas"]["EvidenceFactorResponse"][];
      /** Generated At */
      generated_at: string | null;
      instrument: components["schemas"]["EvidenceInstrumentResponse"];
      market_snapshot: components["schemas"]["EvidenceMarketSnapshotResponse"];
      /** Missing Fields */
      missing_fields: string[];
      /** Pack Hash */
      pack_hash: string;
      /** Pack Id */
      pack_id: string | null;
      /** Schema Version */
      schema_version: string;
      /** Source Refs */
      source_refs: components["schemas"]["EvidenceSourceReferenceResponse"][];
      /** Warnings */
      warnings: string[];
    };
    /** EvidenceSourceReferenceResponse */
    EvidenceSourceReferenceResponse: {
      /**
       * Observed Date
       * Format: date
       */
      observed_date: string;
      /** Quality Status */
      quality_status: string;
      /** Revision */
      revision: number | null;
      /** Source Kind */
      source_kind: string;
      /** Source Ref */
      source_ref: string;
    };
    /**
     * ExclusionReasonResponse
     * @description Machine-readable reason an instrument was excluded.
     */
    ExclusionReasonResponse: {
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /** ExternalArtifactResponse */
    ExternalArtifactResponse: {
      /**
       * Artifact Id
       * Format: uuid
       */
      artifact_id: string;
      /** Content Hash */
      content_hash: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Logical Uri */
      logical_uri: string;
      /** Media Type */
      media_type: string;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      };
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /** Size Bytes */
      size_bytes: number;
    };
    /** ExternalObservationResponse */
    ExternalObservationResponse: {
      /** Admission Status */
      admission_status: string;
      /** Artifact Id */
      artifact_id?: string | null;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Instrument Id */
      instrument_id?: string | null;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      };
      /**
       * Observation Id
       * Format: uuid
       */
      observation_id: string;
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /** Producer */
      producer: string;
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /** Source Uri */
      source_uri: string;
      /** Symbol */
      symbol?: string | null;
    };
    /** ExternalWorkflowRunListResponse */
    ExternalWorkflowRunListResponse: {
      /** Items */
      items: components["schemas"]["ExternalWorkflowRunResponse"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** ExternalWorkflowRunResponse */
    ExternalWorkflowRunResponse: {
      /** Finished At */
      finished_at?: string | null;
      /** Intake Status */
      intake_status: string;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      };
      /** Producer */
      producer: string;
      /** Producer Status */
      producer_status: string;
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /** Schema Version */
      schema_version: string;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Service */
      service: string;
      /** Status */
      status: string;
    };
    /**
     * InstrumentListResponse
     * @description Paginated envelope for the ``GET /api/v1/etf/instruments`` endpoint.
     */
    InstrumentListResponse: {
      /** Items */
      items: components["schemas"]["InstrumentResponse"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /**
     * InstrumentResponse
     * @description Public representation of one ``core.instruments`` row.
     */
    InstrumentResponse: {
      /** Category */
      category?: string | null;
      /** Currency */
      currency: string;
      /** Delist Date */
      delist_date?: string | null;
      /** Exchange */
      exchange: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Instrument Type */
      instrument_type: string;
      /** Is Active */
      is_active: boolean;
      /** List Date */
      list_date?: string | null;
      /** Name */
      name: string;
      /** Status */
      status: string;
      /** Symbol */
      symbol: string;
      /** Underlying Index */
      underlying_index?: string | null;
    };
    /** IntegrationHealthResponse */
    IntegrationHealthResponse: {
      /** Intake Statuses */
      intake_statuses: {
        [key: string]: number;
      };
      /** Latest Run Id */
      latest_run_id?: string | null;
      /** Producer Statuses */
      producer_statuses: {
        [key: string]: number;
      };
      /** Sample Size */
      sample_size: number;
      /** Status */
      status: string;
    };
    /** MarketBreadthObservationResponse */
    MarketBreadthObservationResponse: {
      /** Item Hash */
      item_hash: string;
      /** Observation Key */
      observation_key: string;
      /**
       * Observed Date
       * Format: date
       */
      observed_date: string;
      /** Quality Status */
      quality_status: string;
      /** Source Kind */
      source_kind: string;
      /** Source Ref */
      source_ref: string;
      /** Unit */
      unit: string;
      /** Value */
      value: string | null;
    };
    /** MarketBreadthResponse */
    MarketBreadthResponse: {
      /** Algorithm Version */
      algorithm_version: string;
      /**
       * As Of Date
       * Format: date
       */
      as_of_date: string;
      /** Content Hash */
      content_hash: string;
      /** Freshness Status */
      freshness_status: string;
      /** Input Snapshot Id */
      input_snapshot_id: string;
      /** Observations */
      observations: components["schemas"]["MarketBreadthObservationResponse"][];
      /** Quality Status */
      quality_status: string;
      /** Scope Key */
      scope_key: string;
      /** Scope Type */
      scope_type: string;
      /** Snapshot Id */
      snapshot_id: string;
    };
    /** MarketTemperatureObservationResponse */
    MarketTemperatureObservationResponse: {
      /** Item Hash */
      item_hash: string;
      /** Observation Key */
      observation_key: string;
      /**
       * Observed Date
       * Format: date
       */
      observed_date: string;
      /** Quality Status */
      quality_status: string;
      /** Source Kind */
      source_kind: string;
      /** Source Ref */
      source_ref: string;
      /** Unit */
      unit: string;
      /** Value */
      value: string | null;
    };
    /** MarketTemperatureResponse */
    MarketTemperatureResponse: {
      /** Algorithm Version */
      algorithm_version: string;
      /**
       * As Of Date
       * Format: date
       */
      as_of_date: string;
      /** Content Hash */
      content_hash: string;
      /** Freshness Status */
      freshness_status: string;
      /** Input Snapshot Id */
      input_snapshot_id: string;
      /** Observations */
      observations: components["schemas"]["MarketTemperatureObservationResponse"][];
      /** Quality Status */
      quality_status: string;
      /** Scope Key */
      scope_key: string;
      /** Scope Type */
      scope_type: string;
      /** Snapshot Id */
      snapshot_id: string;
    };
    /**
     * PipelineRunListResponse
     * @description Paginated envelope for the ``GET /api/v1/pipeline-runs`` endpoint.
     *
     * ``total`` counts every ``personal_etf_daily_job`` run (i.e. it is
     * computed independently of ``limit`` / ``offset``) so the UI can
     * render the page count without an extra round trip. ``items`` is
     * always ordered by ``started_at`` descending and then ``id``
     * ascending so successive pages are stable.
     */
    PipelineRunListResponse: {
      /** Items */
      items: components["schemas"]["PipelineRunResponse"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /**
     * PipelineRunResponse
     * @description Public representation of one ``ops.pipeline_runs`` row.
     *
     * Mirrors the storage/domain :class:`invest_domain.pipeline.PipelineRun`
     * fields that PR-03 needs on the read path; storage-internal handles
     * (``dagster_run_id``, ``algorithm_version``, ``config_snapshot``,
     * ``created_at``, ``updated_at``) are deliberately omitted.
     */
    PipelineRunResponse: {
      /** Error Code */
      error_code?: string | null;
      /** Error Summary */
      error_summary?: string | null;
      /** Finished At */
      finished_at?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Job Key */
      job_key: string;
      /** Partition Key */
      partition_key?: string | null;
      /** Started At */
      started_at?: string | null;
      /** Status */
      status: string;
      /** Trigger Type */
      trigger_type: string;
    };
    /** ResearchCaseFromObservationRequest */
    ResearchCaseFromObservationRequest: {
      /**
       * Horizon
       * @default 20-60d
       */
      horizon?: string;
      /** Question */
      question: string;
    };
    /** ResearchCaseFromObservationResponse */
    ResearchCaseFromObservationResponse: {
      /**
       * Case Id
       * Format: uuid
       */
      case_id: string;
      /** Created Case */
      created_case: boolean;
      evidence: components["schemas"]["ResearchExternalEvidenceResponse"];
    };
    /** ResearchCaseListResponse */
    ResearchCaseListResponse: {
      /** Items */
      items: components["schemas"]["ResearchCaseResponse"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** ResearchCaseResponse */
    ResearchCaseResponse: {
      /**
       * As Of Date
       * Format: date
       */
      as_of_date: string;
      /** Candidate Pool Run Id */
      candidate_pool_run_id?: string | null;
      /**
       * Case Id
       * Format: uuid
       */
      case_id: string;
      /** Closed At */
      closed_at?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Horizon */
      horizon: string;
      /**
       * Instrument Id
       * Format: uuid
       */
      instrument_id: string;
      /** Question */
      question: string;
      /** Status */
      status: string;
    };
    /**
     * ResearchCaseWorkspaceResponse
     * @description Composite read-only envelope for the Research Case workspace page.
     *
     * Composes the existing resource shapes so the front-end can render
     * the case, its bound evidence packs, the runs attached to the case
     * and the (nullable) result for each run in a single round trip. The
     * endpoint is the PR-W05 first increment; only the API/backend
     * contract is shipped here.
     *
     * Field invariants:
     *
     * - ``case`` always echoes the canonical case detail shape used by
     *   ``GET /api/v1/research-cases/{case_id}``; the router enforces
     *   the ``case_id`` URL parameter matches the resource.
     * - ``evidence_packs`` is the same list shape as
     *   ``GET /api/v1/research-cases/{case_id}/evidence`` (already
     *   serialised by :class:`EvidencePackResponse`) but is **always
     *   present** - it is ``[]`` rather than omitted when the case has
     *   no bound pack, so the workspace page can render an explicit
     *   empty evidence slot.
     * - ``runs`` is the same per-run shape used by
     *   ``GET /api/v1/research-runs/{run_id}`` and is always present
     *   (the storage repository returns ``[]`` rather than ``None``
     *   when the case has no runs).
     * - ``results`` is **parallel to** ``runs``: ``results[i]``
     *   corresponds to ``runs[i]``; ``results[i] is None`` when the run
     *   has not (yet) produced a result. The pair is never reordered
     *   server-side so the front-end can rely on positional pairing.
     *   The list always carries exactly one entry per run, never an
     *   arbitrary subset.
     *
     * The endpoint is read-only and never invents data: when a run has
     * no published result the workspace exposes a ``null`` slot rather
     * than fabricating one.
     */
    ResearchCaseWorkspaceResponse: {
      case: components["schemas"]["ResearchCaseResponse"];
      /** Evidence Packs */
      evidence_packs?: components["schemas"]["EvidencePackResponse"][];
      /** Results */
      results?: (components["schemas"]["ResearchResultResponse"] | null)[];
      /** Runs */
      runs?: components["schemas"]["ResearchRunResponse"][];
    };
    /**
     * ResearchCenterBreadthResponse
     * @description Market Breadth sub-segment of the contract response.
     *
     * Mirrors :class:`invest_api.application.research_center.ResearchCenterBreadthView`
     * field-by-field. A controlled error is an explicit ``failed``
     * object whose payload fields are null; a genuinely missing snapshot
     * remains ``None``. No identity, scope or observation is fabricated.
     */
    ResearchCenterBreadthResponse: {
      /** Algorithm Version */
      algorithm_version?: string | null;
      /** Observations */
      observations?: components["schemas"]["ResearchCenterObservationResponse"][] | null;
      /** Scope Key */
      scope_key?: string | null;
      /** Scope Type */
      scope_type?: string | null;
      /** Snapshot Id */
      snapshot_id?: string | null;
      /**
       * State
       * @enum {string}
       */
      state: "available" | "failed";
    };
    /**
     * ResearchCenterCapabilitiesResponse
     * @description Slice 1 capability bundle — frozen until later slices land.
     */
    ResearchCenterCapabilitiesResponse: {
      delivery: components["schemas"]["ResearchCenterCapabilityResponse"];
      discipline: components["schemas"]["ResearchCenterCapabilityResponse"];
      opportunities: components["schemas"]["ResearchCenterCapabilityResponse"];
      research: components["schemas"]["ResearchCenterCapabilityResponse"];
      strategy: components["schemas"]["ResearchCenterCapabilityResponse"];
    };
    /**
     * ResearchCenterCapabilityResponse
     * @description One capability entry on the contract response shape.
     *
     * Slice 1 pins every capability to a deterministic placeholder so
     * the response shape is stable and later slices can replace
     * individual entries without re-shaping the application layer.
     */
    ResearchCenterCapabilityResponse: {
      /** Reason */
      reason: string;
      /**
       * State
       * @enum {string}
       */
      state: "deferred" | "unavailable";
    };
    /**
     * ResearchCenterDataFreshnessResponse
     * @description Data Freshness sub-segment of the contract response.
     *
     * ``checked_at`` is the router-stamped UTC wall-clock value the
     * application service intentionally omits; the router reuses the
     * same ``datetime.now(UTC)`` value it stamps on the top-level
     * ``generated_at`` so the two timestamps are always identical for a
     * given response. ``state`` is the four-state substate derived from
     * ``status`` so the UI can render without re-reading the underlying
     * five-state vocabulary; ``status`` carries the original
     * ``fresh | partial | stale | missing | failed`` value verbatim.
     */
    ResearchCenterDataFreshnessResponse: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Daily Bar Count */
      daily_bar_count?: number | null;
      /** Latest Published Trade Date */
      latest_published_trade_date?: string | null;
      /** Missing Count */
      missing_count?: number | null;
      /**
       * State
       * @enum {string}
       */
      state: "available" | "partial" | "unavailable" | "failed";
      /**
       * Status
       * @enum {string}
       */
      status: "fresh" | "partial" | "stale" | "missing" | "failed";
      /** Universe Count */
      universe_count?: number | null;
    };
    /**
     * ResearchCenterMarketResponse
     * @description Market segment of the contract response.
     *
     * ``state`` mirrors the top-level ``state`` for Slice 1 (the
     * contract makes the two equivalent). ``as_of_date`` prefers the
     * breadth snapshot date, falls back to the freshness latest
     * published trade date, and is ``None`` when neither source has a
     * date. ``quality_status`` and ``freshness_status`` carry the
     * breadth domain values verbatim, or ``None`` when no breadth
     * snapshot is available. ``breadth`` and ``data_freshness`` are the
     * per-source sub-segments. Genuine absence is ``None`` while a
     * controlled error is represented by an explicit failed object.
     */
    ResearchCenterMarketResponse: {
      /** As Of Date */
      as_of_date?: string | null;
      breadth?: components["schemas"]["ResearchCenterBreadthResponse"] | null;
      data_freshness?: components["schemas"]["ResearchCenterDataFreshnessResponse"] | null;
      /** Freshness Status */
      freshness_status?: string | null;
      /** Quality Status */
      quality_status?: string | null;
      /**
       * State
       * @enum {string}
       */
      state: "available" | "partial" | "unavailable" | "failed";
    };
    /**
     * ResearchCenterObservationResponse
     * @description One Market Breadth observation on the contract response shape.
     *
     * Maps the application-level
     * :class:`invest_api.application.research_center.ResearchCenterObservationView`
     * onto the public JSON field names: ``observation_key`` is renamed
     * to ``key``; every other observation field is preserved verbatim.
     * ``value`` keeps its native ``Decimal | str | None`` type so
     * Pydantic renders ``Decimal`` as a string (matching the existing
     * Market Breadth endpoint) while a plain textual value stays a
     * string and ``None`` stays ``null``.
     */
    ResearchCenterObservationResponse: {
      /** Key */
      key: string;
      /**
       * Observed Date
       * Format: date
       */
      observed_date: string;
      /** Quality Status */
      quality_status: string;
      /** Source Kind */
      source_kind: string;
      /** Source Ref */
      source_ref: string;
      /** Unit */
      unit: string;
      /** Value */
      value: string | null;
    };
    /**
     * ResearchCenterResponse
     * @description Read-only response envelope for the contract endpoint.
     *
     * Mirrors :class:`invest_api.application.research_center.ResearchCenterResponse`
     * field-by-field and adds the two router-owned timestamps
     * (``generated_at`` and the propagated ``market.data_freshness.checked_at``).
     * Both timestamps come from the same ``datetime.now(UTC)`` call so a
     * single response always observes identical values; the application
     * service intentionally does not own a clock.
     */
    ResearchCenterResponse: {
      capabilities: components["schemas"]["ResearchCenterCapabilitiesResponse"];
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
      market: components["schemas"]["ResearchCenterMarketResponse"];
      /**
       * Schema Version
       * @constant
       */
      schema_version: "1.0.0";
      /**
       * State
       * @enum {string}
       */
      state: "available" | "partial" | "unavailable" | "failed";
    };
    /**
     * ResearchDashboardEvidenceStatus
     * @description Explicit empty / available state for the latest-case evidence slot.
     *
     * The dashboard always reports one of two states:
     *
     * - ``"empty"`` — no cases exist, or the latest case exists but has
     *   no bound ``EvidencePack`` rows. ``case_id`` echoes the case
     *   being reported (when available) so the front-end can deep-link
     *   to it; ``pack_id`` is ``None``.
     * - ``"available"`` — the latest case has at least one bound pack
     *   and the surface carries the pack-level identifiers and quality
     *   metadata. Only the **first** bound pack is summarised; the full
     *   pack list is intentionally not enumerated on the dashboard.
     */
    ResearchDashboardEvidenceStatus: {
      /** Case Id */
      case_id?: string | null;
      /** Factor Set Key */
      factor_set_key?: string | null;
      /** Factor Set Version */
      factor_set_version?: string | null;
      /** Freshness Status */
      freshness_status?: string | null;
      /** Pack Id */
      pack_id?: string | null;
      /** Quality Status */
      quality_status?: string | null;
      /** Schema Version */
      schema_version?: string | null;
      /**
       * State
       * @enum {string}
       */
      state: "empty" | "available";
    };
    /**
     * ResearchDashboardMarketStatus
     * @description Explicit empty state for the dashboard's ``market_status`` slot.
     *
     * The PR-W03 dashboard deliberately does **not** invent market /
     * factor values. No market dashboard source is registered yet, so
     * the only legal response is ``state = "unavailable"`` with a
     * machine-readable ``reason`` so downstream consumers can render a
     * stable empty placeholder rather than fabricating numbers.
     */
    ResearchDashboardMarketStatus: {
      /**
       * Reason
       * @description Stable identifier explaining why the market dashboard slot is empty. The PR-W03 dashboard never invents market values, so the only legal reason is that no market dashboard source is registered.
       */
      reason: string;
      /**
       * State
       * @constant
       */
      state: "unavailable";
    };
    /**
     * ResearchDashboardResearchSummary
     * @description Deterministic counts and the latest case for the dashboard.
     *
     * ``case_count`` / ``run_count`` are derived from the storage
     * readers' ``count_all`` so the values are exact, not bounded by the
     * ``recent_runs`` cap. ``latest_case`` is the first row of the
     * case reader's deterministic ``created_at`` descending ordering,
     * or ``None`` when no cases exist; the dashboard never reaches into
     * a different ordering or derives a "best" case heuristically.
     */
    ResearchDashboardResearchSummary: {
      /** Case Count */
      case_count: number;
      latest_case?: components["schemas"]["ResearchCaseResponse"] | null;
      /** Run Count */
      run_count: number;
    };
    /**
     * ResearchDashboardResponse
     * @description Response envelope for the ``GET /api/v1/research-dashboard`` endpoint.
     *
     * The dashboard is a read-only aggregate over the existing PR-7
     * resource-level endpoints so the front-end can render the cockpit
     * first screen with a single round trip. Every field is derived
     * strictly from existing :class:`ResearchCase` /
     * :class:`ResearchRun` / :class:`EvidencePack` storage state; no
     * market / factor values or investment conclusions are invented on
     * this path.
     *
     * - ``schema_version`` is the response contract version (currently
     *   ``"1.0.0"``); it is independent of the evidence-pack schema
     *   version reported under ``evidence_status``.
     * - ``generated_at`` is the UTC wall-clock stamp the router applies
     *   when it builds the response (two callers hitting the service in
     *   the same instant observe different timestamps).
     * - ``as_of_date`` echoes the latest ``ResearchCase.as_of_date`` so
     *   the front-end can label the dashboard without a follow-up
     *   round trip; ``None`` when no cases exist.
     * - ``data_quality`` and ``freshness`` use the coarse PR-W03
     *   vocabularies documented on :data:`ResearchDashboardDataQuality`
     *   and :data:`ResearchDashboardFreshness`.
     * - ``market_status`` is always the explicit
     *   ``{"state": "unavailable", "reason": "..."}`` shape until a
     *   market dashboard source is registered.
     * - ``evidence_status`` distinguishes the empty case from the
     *   available case; when ``available`` the surface carries the pack
     *   identifiers and the existing ``QualityStatus`` /
     *   ``FreshnessStatus`` enum strings.
     * - ``recent_runs`` is a bounded page (the same shape
     *   :class:`ResearchRunResponse` already used by
     *   ``/api/v1/research-runs``) so consumers can compose the
     *   dashboard timeline widget without fanning out to the
     *   resource-level endpoint.
     */
    ResearchDashboardResponse: {
      /** As Of Date */
      as_of_date?: string | null;
      /**
       * Data Quality
       * @enum {string}
       */
      data_quality: "empty" | "partial" | "complete";
      evidence_status: components["schemas"]["ResearchDashboardEvidenceStatus"];
      /**
       * Freshness
       * @enum {string}
       */
      freshness: "unknown" | "current" | "stale";
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
      market_status: components["schemas"]["ResearchDashboardMarketStatus"];
      /** Recent Runs */
      recent_runs?: components["schemas"]["ResearchRunResponse"][];
      research_summary: components["schemas"]["ResearchDashboardResearchSummary"];
      /** Schema Version */
      schema_version: string;
    };
    /** ResearchExternalEvidenceResponse */
    ResearchExternalEvidenceResponse: {
      /** Admission */
      admission: {
        [key: string]: unknown;
      };
      /** Artifact Content Hash */
      artifact_content_hash: string | null;
      /** Artifact Id */
      artifact_id: string | null;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Content Hash */
      content_hash: string;
      /** Evidence Id */
      evidence_id: string;
      /**
       * Observation Id
       * Format: uuid
       */
      observation_id: string;
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /** Producer */
      producer: string;
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /** Source Uri */
      source_uri: string;
    };
    /** ResearchResultResponse */
    ResearchResultResponse: {
      /** Adapter Version */
      adapter_version: string;
      /** Conclusion */
      conclusion: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Evidence Ids */
      evidence_ids: string[];
      /**
       * Evidence Pack Id
       * Format: uuid
       */
      evidence_pack_id: string;
      /** Model Key */
      model_key: string;
      /** Model Version */
      model_version: string;
      /** Playbook Version */
      playbook_version: string;
      /** Report Markdown */
      report_markdown: string;
      /**
       * Result Id
       * Format: uuid
       */
      result_id: string;
      /** Risks */
      risks: string[];
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
    };
    /** ResearchRunCommandRequest */
    ResearchRunCommandRequest: {
      /**
       * Evidence Pack Id
       * Format: uuid
       */
      evidence_pack_id: string;
      /** Playbook Key */
      playbook_key: string;
      /** Playbook Version */
      playbook_version: string;
    };
    /** ResearchRunCommandResponse */
    ResearchRunCommandResponse: {
      /** Idempotent */
      idempotent: boolean;
      run: components["schemas"]["ResearchRunResponse"];
    };
    /** ResearchRunListResponse */
    ResearchRunListResponse: {
      /** Items */
      items: components["schemas"]["ResearchRunResponse"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** ResearchRunResponse */
    ResearchRunResponse: {
      /** Attempt */
      attempt: number;
      /**
       * Case Id
       * Format: uuid
       */
      case_id: string;
      /** Error Summary */
      error_summary: string | null;
      /**
       * Evidence Pack Id
       * Format: uuid
       */
      evidence_pack_id: string;
      /** Finished At */
      finished_at: string | null;
      /** Playbook Key */
      playbook_key: string;
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /** Runner Key */
      runner_key: string;
      /** Started At */
      started_at: string | null;
      /** Status */
      status: string;
    };
    /**
     * RuleOutcomeResponse
     * @description Outcome of one rule applied to one instrument in a pool.
     */
    RuleOutcomeResponse: {
      /** Message */
      message?: string | null;
      /** Passed */
      passed: boolean;
      /** Rule Key */
      rule_key: string;
      /** Severity */
      severity: string;
      /** Threshold */
      threshold?: string | null;
      /** Value */
      value?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get Latest Candidate Pool
   * @description Return the most recently published candidate-pool run.
   */
  get_latest_candidate_pool_api_v1_candidate_pool_latest_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CandidatePoolLatestResponse"];
        };
      };
    };
  };
  /**
   * Get Latest Candidate Pool Diff
   * @description Diff the latest published run against the previous earlier published run.
   */
  get_latest_candidate_pool_diff_api_v1_candidate_pool_latest_diff_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CandidatePoolDiffResponse"];
        };
      };
    };
  };
  /**
   * Get Candidate Pool Diff
   * @description Diff the published run identified by ``run_id`` against its predecessor.
   *
   * Returns 404 when ``run_id`` does not exist or the run is not in the
   * ``PUBLISHED`` state; the diff itself is read-only and never mutates
   * storage state.
   */
  get_candidate_pool_diff_api_v1_candidate_pool__run_id__diff_get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CandidatePoolDiffResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Data Freshness
   * @description Return the data-freshness summary for ``expected_trade_date``.
   *
   * The application service applies the ``expected_trade_date`` default
   * (latest weekday from :func:`invest_api.clock.market_today`), runs
   * the snapshot / published / empty fallback chain and the
   * status-state-machine reduction, and packages the outcome into a
   * small :class:`DataFreshnessView` dataclass. The router only maps
   * that view onto the public Pydantic response shape and converts
   * :class:`DataFreshnessQueryError` into a sanitized HTTP 500.
   */
  get_data_freshness_api_v1_data_freshness_get: {
    parameters: {
      query?: {
        expected_trade_date?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DataFreshnessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Etf Daily Bars
   * @description Return the latest revision per trade_date for one instrument.
   */
  list_etf_daily_bars_api_v1_etf_daily_bars_get: {
    parameters: {
      query: {
        instrument_id: string;
        start_date: string;
        end_date: string;
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DailyBarListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Etf Instruments
   * @description Return the active ETF master data, optionally filtered by exchange/status.
   */
  list_etf_instruments_api_v1_etf_instruments_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        exchange?: string | null;
        status?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InstrumentListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Decide Admission */
  decide_admission_api_v1_external_observations__observation_id__admission_decisions_post: {
    parameters: {
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path: {
        observation_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdmissionDecisionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AdmissionDecisionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List External Workflows */
  list_external_workflows_api_v1_external_workflows_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ExternalWorkflowRunListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get External Workflow */
  get_external_workflow_api_v1_external_workflows__run_id__get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ExternalWorkflowRunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List External Artifacts */
  list_external_artifacts_api_v1_external_workflows__run_id__artifacts_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ExternalArtifactResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List External Observations */
  list_external_observations_api_v1_external_workflows__run_id__observations_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ExternalObservationResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Preview Artifact */
  preview_artifact_api_v1_integration_artifacts__artifact_id__get: {
    parameters: {
      path: {
        artifact_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ArtifactPreviewResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Integration Health */
  get_integration_health_api_v1_integration_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["IntegrationHealthResponse"];
        };
      };
    };
  };
  /**
   * Get Latest Market Breadth
   * @description Return the latest Market Breadth snapshot for ``as_of_date``.
   *
   * ``as_of_date`` is optional: omitting it asks the service for the
   * newest snapshot regardless of trade date; supplying a value
   * narrows the lookup to that exact date. The application service
   * pins ``scope_type`` / ``scope_key`` so the route never reads a
   * sibling ``scope_type`` family (e.g. ``market_temperature``)
   * through the breadth surface.
   */
  get_latest_market_breadth_api_v1_market_breadth_latest_get: {
    parameters: {
      query?: {
        as_of_date?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MarketBreadthResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Latest Market Temperature */
  get_latest_market_temperature_api_v1_market_temperature_latest_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MarketTemperatureResponse"];
        };
      };
    };
  };
  /** List Opportunity Radar */
  list_opportunity_radar_api_v1_opportunity_radar_get: {
    parameters: {
      query?: {
        admission_status?: ("pending" | "corroborated" | "admitted" | "rejected" | "conflict") | null;
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ExternalObservationResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Pipeline Runs
   * @description Return a paginated history of ``personal_etf_daily_job`` runs.
   *
   * The application service applies the ``job_key`` filter, limit and
   * offset in SQL and supplies the exact total from its companion
   * count query. ``PipelineRunQueryError`` (raised when the underlying
   * repository raises ``SQLAlchemyError``) is caught and re-raised as a
   * sanitized HTTP 500.
   */
  list_pipeline_runs_api_v1_pipeline_runs_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PipelineRunListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Latest Pipeline Run
   * @description Return the most recent run of the personal daily job.
   *
   * The application service walks the repository's ``list_recent``
   * page - ordered by ``started_at`` descending - and returns the first
   * run matching ``job_key = "personal_etf_daily_job"``. The router
   * surfaces ``404`` when no matching run exists; any run that resolves
   * to a different ``job_key`` is intentionally ignored.
   */
  get_latest_pipeline_run_api_v1_pipeline_runs_latest_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PipelineRunResponse"];
        };
      };
    };
  };
  /**
   * Get Pipeline Run By Id
   * @description Return the run for ``run_id`` if it belongs to the personal daily job.
   *
   * A missing run OR a run that resolves to a different ``job_key`` both
   * surface as ``404``; the front-end cannot distinguish between "the
   * UUID does not exist" and "the UUID belongs to a different job".
   */
  get_pipeline_run_by_id_api_v1_pipeline_runs__run_id__get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PipelineRunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Research Cases */
  list_research_cases_api_v1_research_cases_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ResearchCaseListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Case From Observation */
  create_case_from_observation_api_v1_research_cases_from_external_observations__observation_id__post: {
    parameters: {
      path: {
        observation_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResearchCaseFromObservationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ResearchCaseFromObservationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Research Case */
  get_research_case_api_v1_research_cases__case_id__get: {
    parameters: {
      path: {
        case_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ResearchCaseResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Research Case Evidence */
  get_research_case_evidence_api_v1_research_cases__case_id__evidence_get: {
    parameters: {
      path: {
        case_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EvidencePackResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Link External Observation */
  link_external_observation_api_v1_research_cases__case_id__external_observations__observation_id__evidence_post: {
    parameters: {
      path: {
        case_id: string;
        observation_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ResearchExternalEvidenceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Queue Research Run */
  queue_research_run_api_v1_research_cases__case_id__runs_post: {
    parameters: {
      path: {
        case_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResearchRunCommandRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ResearchRunCommandResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Research Case Workspace
   * @description Return the read-only case workspace envelope (PR-W05 first increment).
   *
   * The endpoint composes the existing
   * ``ResearchCaseResponse`` / ``EvidencePackResponse`` /
   * ``ResearchRunResponse`` / ``ResearchResultResponse`` resource
   * shapes; no new resource field is invented. ``results`` is the
   * positional, parallel companion of ``runs`` so the front-end can
   * pair them by index; a ``null`` result slot is exposed for runs
   * that have not (yet) published a result rather than fabricating
   * one. The endpoint is the read-only API contract for the future
   * workspace page; the front-end itself is not part of this PR.
   *
   * Errors:
   *
   * - ``404`` when the case does not exist (the same detail string
   *   as ``GET /api/v1/research-cases/{case_id}`` so callers can
   *   share error handlers).
   * - ``500`` with the sanitized ``"Research query failed"`` detail
   *   on :class:`ResearchQueryError`, consistent with the existing
   *   endpoints.
   * - ``422`` for a malformed ``case_id`` UUID (FastAPI default).
   */
  get_research_case_workspace_api_v1_research_cases__case_id__workspace_get: {
    parameters: {
      path: {
        case_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ResearchCaseWorkspaceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Research Center
   * @description Return the Slice 1 Research Center contract response.
   *
   * The handler owns a single UTC wall-clock value and reuses it for
   * both ``generated_at`` and ``market.data_freshness.checked_at`` so
   * the two timestamps are always identical. The application service
   * converts the two underlying sources' controlled errors into
   * explicit failed sub-segments before this router sees them; any
   * other exception is intentionally allowed to propagate so FastAPI's
   * generic error boundary (and not this router) sanitises the
   * response. The endpoint is intentionally GET-only — no POST, PUT,
   * PATCH or DELETE handlers exist on this router and the OpenAPI
   * spec reflects that.
   */
  get_research_center_api_v1_research_center_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ResearchCenterResponse"];
        };
      };
    };
  };
  /**
   * Get Research Dashboard
   * @description Return the read-only Research Cockpit dashboard aggregate.
   *
   * The dashboard derives every field from the existing PR-7
   * resource-level readers (``ResearchCaseReader`` /
   * ``ResearchRunReader`` / ``ResearchEvidenceReader``). The
   * application service owns the orchestration, the deterministic
   * ordering, the bounded ``recent_runs`` list and the
   * ``SQLAlchemyError`` boundary; this router is intentionally a
   * thin pass-through that stamps ``generated_at`` with a UTC
   * wall-clock value so two callers hitting the service in the
   * same instant still observe distinct response timestamps.
   *
   * ``market_status`` is always the explicit
   * ``{"state": "unavailable", "reason": "..."}`` shape until a
   * market dashboard source is registered; no market / factor
   * values or investment conclusions are invented on this path.
   */
  get_research_dashboard_api_v1_research_dashboard_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ResearchDashboardResponse"];
        };
      };
    };
  };
  /** List Research Runs */
  list_research_runs_api_v1_research_runs_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ResearchRunListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Research Run */
  get_research_run_api_v1_research_runs__run_id__get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ResearchRunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Research Run Result */
  get_research_run_result_api_v1_research_runs__run_id__result_get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ResearchResultResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /** List Instruments */
  list_instruments_v1_instruments_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InstrumentListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
